[package]
name = "nala"
version = "0.1.0"
authors = ["Nathan Wiles <ntwiles@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
nala_interpreter = { path = "nala_interpreter"}

[dev-dependencies]
test_util = { path = "test_util" }
regex = "1.5.4"


