[package]
name = "nala-rust"
version = "0.1.0"
authors = ["Nathan Wiles <ntwiles@gmail.com>"]
edition = "2018"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"