use std::str::FromStr;
use crate::ast;

grammar;

pub Stmt: ast::Stmt = {
    "print" <Literal> ";" => ast::Stmt::Print(<>),
};

Literal: ast::Literal = {
    <n:NumLiteral> => ast::Literal::Num(n),
    <s:StrLiteral> => ast::Literal::String(s)
}

NumLiteral: i32 = {
    r"[0-9]+" => i32::from_str(<>).unwrap(),
}

StrLiteral: String = {
    <s:r"'[a-zA-z0-9\s]*'"> => 
        String::from_str(&s[1..s.len() - 1]).unwrap(),
};